remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


# Site Settings
locale                   : "ja-JP"
layout: default
title: rickyban's portfolio
# description: rickyban's portfolio
# url                      : "https://rickyban.github.io/"
# repository               : "RIckyBan/RickyBan.github.io"
logo: images/icon.jpg